### ISSUE TITLE
[Bug] no attribute default_value

### ISSUE THREAD

**Issue by rmm286** [njanakiev/blender-scripting-intro#11]
**Context**
I am a first time user to blender scripting. I am working with Blender 2.82 (sub 7) (2.82.a+dfsg-1). I am on Ubuntu 20.04.

**Whats Wrong**
When running several of the scripts following the Readme, including `simple_sphere.py` and `fisher_iris_visualization.py`, I am getting an Attribute Error on default_value. 

AttributeError: 'NodeSocketShader' object has no attribute 'default_value'

**Expected Behavior**
When I checkout [`8359200`](https://github.com/njanakiev/blender-scripting/commit/8359200534d5a3a58ab9de8dca49086c72399353), I am able to run the script successfully.

Looks like this is a recent change so I assume I am doing something wrong, I made sure blender was updated and ran it using the command given on the readme, but I am not sure what I might be doing wrong.
